name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Run Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }} 
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ secrets.SSH_FOLDER }}
            git pull
            chmod u+x ./bin/extend.go
            go run ./bin/extend.go
            cd storefront
            git pull
            bun install
            bun run build
            cd .. && docker compose down && docker compose up -d
